INSERT INTO COMPLAINT
(
    student_id,
    faculty_id,
    complaint_date,
    complaint_type,
    subject,
    description,
    priority,
    complaint_status,
    resolution_date,
    resolution_remarks
)
VALUES

(1, NULL, '2026-09-01 09:30:00',
 'FACILITY',
 'Computer Laboratory AC not working',
 'Air conditioning in the computer laboratory is not functioning properly.',
 'HIGH',
 'IN_PROGRESS',
 NULL,
 NULL),

(2, NULL, '2026-09-02 11:15:00',
 'CLEANLINESS',
 'Laboratory cleanliness issue',
 'Computer laboratory requires cleaning before practical sessions.',
 'MEDIUM',
 'RESOLVED',
 '2026-09-03 10:00:00',
 'Cleaning staff assigned and laboratory cleaned.'),

(NULL, 1, '2026-09-03 14:20:00',
 'EQUIPMENT',
 'Projector display problem',
 'Projector display quality has deteriorated during classroom presentations.',
 'MEDIUM',
 'IN_PROGRESS',
 NULL,
 NULL),

(5, NULL, '2026-09-04 10:45:00',
 'ELECTRICAL',
 'Power socket not working',
 'One of the electrical sockets in the laboratory is not functioning.',
 'HIGH',
 'OPEN',
 NULL,
 NULL),

(6, NULL, '2026-09-05 13:10:00',
 'NETWORK',
 'Slow internet connection',
 'Internet connectivity is very slow during practical sessions.',
 'HIGH',
 'IN_PROGRESS',
 NULL,
 NULL),

(NULL, 4, '2026-09-06 09:00:00',
 'FACILITY',
 'Faculty room lighting issue',
 'Two ceiling lights in the faculty room are not working.',
 'LOW',
 'RESOLVED',
 '2026-09-07 11:30:00',
 'Faulty lights replaced.'),

(9, NULL, '2026-09-07 15:40:00',
 'SECURITY',
 'Laboratory access issue',
 'Student access to the laboratory was unavailable during scheduled project work.',
 'MEDIUM',
 'OPEN',
 NULL,
 NULL),

(10, NULL, '2026-09-08 12:25:00',
 'CLEANLINESS',
 'Classroom cleaning required',
 'Classroom was not cleaned before the scheduled practical session.',
 'LOW',
 'RESOLVED',
 '2026-09-09 09:15:00',
 'Room cleaned by housekeeping staff.'),

(NULL, 8, '2026-09-09 16:00:00',
 'EQUIPMENT',
 'Laboratory equipment calibration',
 'Laboratory equipment requires periodic calibration.',
 'HIGH',
 'IN_PROGRESS',
 NULL,
 NULL),

(12, NULL, '2026-09-10 10:30:00',
 'FACILITY',
 'Broken classroom chair',
 'One classroom chair is damaged and requires replacement.',
 'LOW',
 'OPEN',
 NULL,
 NULL),

(13, NULL, '2026-09-11 14:15:00',
 'ELECTRICAL',
 'Electrical fluctuation',
 'Frequent power fluctuations were observed during laboratory usage.',
 'CRITICAL',
 'IN_PROGRESS',
 NULL,
 NULL),

(NULL, 3, '2026-09-12 11:00:00',
 'NETWORK',
 'Network connectivity issue',
 'Network connectivity in the department is intermittent.',
 'HIGH',
 'OPEN',
 NULL,
 NULL),

(16, NULL, '2026-09-13 13:35:00',
 'FACILITY',
 'Project room maintenance',
 'Project room requires minor maintenance before student project work.',
 'MEDIUM',
 'OPEN',
 NULL,
 NULL),

(17, NULL, '2026-09-14 09:50:00',
 'CLEANLINESS',
 'Seminar room cleaning',
 'Seminar room requires cleaning after an event.',
 'LOW',
 'CLOSED',
 '2026-09-14 14:00:00',
 'Cleaning completed and room inspected.');
